apiVersion: v1
kind: Service
metadata:
  name: yyc-smart-office
  namespace: yyc
spec:
  type: ClusterIP
  selector:
    app: yyc-smart-office
  ports:
    - name: http
      port: 80
      targetPort: 3000
